spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

server:
  port: 8080